Review for Project 6
paulzay/The-next-web pull request #3
Opened 2020-05-28 15:59 UTC by chelmerrox

We have completed this project and have divided our web page as such:

   1. Nav-top container

   2. Grid-container-1

   3. Flex-container-2

   4. Flex-container-3

   5. Grid-container-2

   6. Articles section

   7. Latest funding section

   8. Apps, Gear, tech etc section

   9. Latest deals section

   10. Footer container

We've also built & styled the webpage for each of the 3 screen sizes:

    - Mobile screen (Max-width: 375px)
    - Tablet screen (Min-width: 376px and Max-width: 767px)
    - Laptop/Desktop screen (Min-width: 768px)

2020-05-28 19:05 UTC, rammazzoti2000 commented
## Pull request under review by Alexandru Bangau (TSE)

2020-05-28 21:34 UTC, rammazzoti2000 requested changes
### Hello team :wave: I am Alex, your code reviewer for this project
You have done great job, there are still some errors to fix before approving this project, see comments bellow
### :stop_sign: Required Changes :construction: :construction_worker: 
- [ ] The HTML did not pass validation, consider using [this validator](https://validator.w3.org/#validate_by_upload) to fix the errors
![image](https://user-images.githubusercontent.com/3244654/83190289-7ca75800-a132-11ea-9adb-74ac0b2d46e9.png)
- [ ] The typography definitely needs improvements, I made some suggestions in the inline comments to make your typography more responsive and look more like the original, mainly:
```
html {
    font-family: Helvetica, Arial, sans-serif;
    font-size: 60%; --> makes the font responsive based on the local settings of the browser and sets the root size of the fonts to 60% (medium) this will give you the chance to set the font-size of your page using rem units, which in this case 10px will be 1rem, 11.5px will be 1.15rem etc.
}
```
- [ ] On medium screens the TWN logo appears at the leftmost part ([link to page](https://thenextweb.com/))
- [ ] On small screens the logo looks distorted, also the first row on main content it behaves weird and has extra content overlay, please fix it
![image](https://user-images.githubusercontent.com/3244654/83191636-a3ff2480-a134-11ea-8ed2-2306bd2e5a2c.png)
##
### The `Latest News` section
- [ ] The `Latest Deals` section on top should be called `Latest News`
- [ ] On medium screens it should align 3 article per row
#### Original:
![image](https://user-images.githubusercontent.com/3244654/83192552-fee54b80-a135-11ea-99f9-2cb963de8f14.png)
### Clone: 
![image](https://user-images.githubusercontent.com/3244654/83192703-3522cb00-a136-11ea-8dc5-fb717a077cdf.png)
- [ ] On small screens the picture is of different size and is quite big
### Clone:
![image](https://user-images.githubusercontent.com/3244654/83193208-ec1f4680-a136-11ea-9b23-67516a72b489.png)
### Original:
![image](https://user-images.githubusercontent.com/3244654/83193420-4ae4c000-a137-11ea-84b9-b272011f783e.png)
### The `Latest Funding` section
- [ ] On medium screens it aligns 3 articles per row ([link to page](https://thenextweb.com/)) and the links on the right will align in a row on the left side
- [ ] On small screens the pictures of each latest fund are a bit messy, please fix it
![image](https://user-images.githubusercontent.com/3244654/83194055-508ed580-a138-11ea-92b4-1d317c838ea3.png)
### The `Categories (Apps, Gear, Tech, etc)` section
- [ ] On medium screens it aligns 2 category boxes per row ([link to page](https://thenextweb.com/))
### The `Latest deals` section
- [ ] On medium screens It aligns 3 deals per row ([link to page](https://thenextweb.com/))
- [ ] On small screens the picture is of different size is quite big (same problem as in the latest news section)
### The `Footer` section
- [ ] It should not change through breakpoints** ([link to page](https://thenextweb.com/)), but yours does :point_down: 
#### On medium screens and large screens:
![image](https://user-images.githubusercontent.com/3244654/83195384-6dc4a380-a13a-11ea-952a-4cde9adaae56.png)
#### On small screens:
![image](https://user-images.githubusercontent.com/3244654/83195536-a6fd1380-a13a-11ea-91a3-e0db89cc06b5.png)
### Important :exclamation: 
Considering this project to be a clone of [the original](https://thenextweb.com/) one, it should look alike as much as possible. I invite you to take a moment of observation and compare your project against the original one, does it look the same, what needs to be changed, what can be improved :eyes: :question: 
At this point based on the changes required and the answer to the question I asked you, please submit for a new review once you feel ready.
### <em>Kindly fix the REQUIRED issues and send another code review request.

Cheers and Happy coding! :clap: 

Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>
### :stop_sign: Status: Required Changes

2020-05-28 21:34 UTC, rammazzoti2000 commented on assets/styles/index.css
> +html {
The typography needs some improvements
`font-family: Helvetica Neue, Arial, sans-serif` --> this will improve the typography style
`font-size: 60%;` [OPTIONAL] --> adding font-size: 60%  to the html tag will make the font responsive based on the setting of the browser itself and will give you the chance to add size to the font-size based on the root of the page meaning that `font-size: 10px;` will be equivalent to `font-size: 1rem;` giving you flexibility to have a responsive font size

2020-05-28 21:34 UTC, rammazzoti2000 commented on assets/styles/index.css
> +  /* .latest {
no commented code, please consider removing it

2020-05-28 21:34 UTC, rammazzoti2000 commented on assets/styles/index.css
> +  /* .flex-container-3 span {
no commented code, please consider removing it

2020-05-28 21:34 UTC, rammazzoti2000 commented on index.html
> +        <ul class="grid-container-3-links">
each `li` element in `grid-container-3-links` has <`br`> tag and is preventing the text to fully stretch making the style looking odd.
please consider removing all the <br> tag from the `li` elements in all `grid-container-3-links` containers

2020-05-28 21:34 UTC, rammazzoti2000 commented on assets/styles/index.css
> +  .grid-container-3-links li {
To make bullet  `li` elements look like the original add .`grid-container-3-links li` the following rules:
```
list-style: disc;
color: red;
font-size: 1.4rem; --> now you can use responsive font-size since the root size of the fonts is now set to 60%.
```
this way you don't need the `::before` content property, also because you can see a mismatch in the style

2020-05-28 21:34 UTC, rammazzoti2000 commented on assets/styles/index.css
> +  .flex-container-4 {
If you implemented the Optional `font-size: 60%;` in <`html`> tag above then adding `font-size: 1.5rem;` will increase the font-size based on the root of the page
##
`align-items: center` will center vertically the content
`padding-left: 10px;`

2020-05-28 21:34 UTC, rammazzoti2000 commented on assets/styles/index.css
> +  .socials ul {
`list-style: none` to remove the bullets on each `li` element

2020-05-28 21:34 UTC, rammazzoti2000 commented on assets/styles/index.css
> +  .links ul {
`list-style: none;` to remove the bullets from each `li` elements

2020-05-30 01:11 UTC, trekab requested changes
# Changes Required! :recycle: 
Hi @chelmerrox and @paulzay! You have done a great job making your clone responsive and following the mobile-first approach. However, there are a few changes you need to make. These will make your clone appear more like the original site:
- [ ] For large screens, `Latest news`, `Latest Funding`, `Categories (Apps, Gear, Tech, etc)`, and `Latest deals` sections should be centered with some space to the left and right. ([link to page](https://thenextweb.com/))
- [ ] Your font size is bigger than the font size of the original site, especially for the `Categories (Apps, Gear, Tech, etc)` section. This makes your clone look less like the original. Try to size your fonts more proportionally. 

### Optional:
- [ ] It is a good practice to make use of [semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp) elements whenever possible. For example, I have noticed that you could have used the [`<nav>` tag](http://html5doctor.com/nav-element/) for the major navigation links and the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>`.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review_ :wink: 
__Treasure Kabareebe__

2020-05-30 05:25 UTC, sumancrest0001 approved these changes
**STATUS: APPROVED :fire: :fire: 
Congratulation team :clap: :+1:** 
You have done a terrific job to make it similar to the original page. The layout looks good and it is responsive. It's a green signal from my side. Now, you can merge the PR to master and move to the next project. Before that, I encourage to make the following optional changes to make it better.

[Optional] Let's reduce the font-size of article titles on a medium screen.
[Optional] Let's use more semantic HTML elements which help for better SEO. [this article](https://www.w3schools.com/html/html5_semantic_elements.asp) might be helpful to you.

**Happy coding !!!**

2020-05-30 05:28 UTC, merged